version: "3.4"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    volumes:
      - "zookeeper_data:/var/lib/zookeeper/data"
      - "zookeeper_log:/var/lib/zookeeper/log"
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    volumes:
      - "kafka_data:/var/lib/kafka/data"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - 18080:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - "mongo_data:/data/db"
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - "mysql_data:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=techbankRootPsw
  postgresql:
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - "postgresql_data:/var/lib/postgresql"
    environment:
      - POSTGRES_PASSWORD=techbankRootPsw
      - POSTGRES_USER=techbankRoot
      - POSTGRES_DB=bankAccount

volumes:
  kafka_data:
  zookeeper_data:
  zookeeper_log:
  mongo_data:
  mysql_data:
  postgresql_data:

